name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Mnaual Trigger"
        default: "MT"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: 
          - 3.9
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: py.test --cov --cov-report=xml owm tests -vv
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          args: >
            -Dsonar.organization=verveK_lg24devsecops 
            -Dsonar.projectKey=jgennari-2023-devsecops-example 
            -Dsonar.sources=owm/
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }} 
      - name: Pyre Action
        uses: facebook/pyre-action@v0.0.1
        with:
          # Path to the python source code you want to type check. If you want to type check the root of your repo, use './'. A .pyre_configuration file should exist here, if not, a default configuration will be used.
          repo-directory: './'
          requirements-path: './requirements.txt'
       
     

